### ISSUE TITLE
[FOSSA] Issue with test-spec - UNLICENSED_DEPENDENCY

### ISSUE THREAD

**Issue by shedd** [RenoFi/fishplate#26]
### Component URL
http://test-spec.rubyforge.org

### Affected Projects
- fishplate

### Issue
This dependency hasn't specified a license. You may need to contact the author to obtain permission to use it.

No licenses found by FOSSA.

---

Generated by [FOSSA](https://fossa.com) on 02/29/2020
Reported by FOSSA user: robert@renofi.com

**Comment by shedd** [comment]
@knapo similar issue as to #25 with test-spec. No license on Rubygems and homepage appears to be down - https://rubygems.org/gems/test-spec/versions/0.2

**Comment by knapo** [comment]
Same as https://github.com/RenoFi/fishplate/issues/25, `test-spec` is not a fishplate dependency.

**Comment by shedd** [comment]
@knapo FOSSA is saying this is an underlying dependency of `rack-contrib`:

![Screen Shot 2020-02-29 at 1 13 41 PM](https://user-images.githubusercontent.com/180497/75612991-b9918d80-5af6-11ea-8fd4-d2be57cbb025.png)

But I don't see it in the rack-contrib gemfile: https://github.com/rack/rack-contrib/blob/master/rack-contrib.gemspec

I'll ask FOSSA about this one.

**Comment by knapo** [comment]
Interesting, I wonder it's a bug or some hidden dependency scanning.

**Comment by shedd** [comment]
FOSSA finally followed up on this - apparently they've spidered it out of the rack-contrib readme:

```
Looks like we're picking it up from the Readme.md:
https://github.com/rack/rack-contrib/search?q=test-spec&unscoped_q=test-spec
```

Marked as resolved.

**Comment by knapo** [comment]
That's funny actually, that they rely on readme content to list dependencies ;)

**Comment by shedd** [comment]
Would love to see examples where that actually returns true dependencies that can't be determined otherwise 😄
